package com.example.webapp.service;

import com.example.webapp.entity.HealthCheck;
import com.example.webapp.repository.HealthCheckRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

@Service
public class HealthCheckService {

    private final HealthCheckRepository repository;

    public HealthCheckService(HealthCheckRepository repository) {
        this.repository = repository;
    }


    /**
    * Records a new health check entry in the system.
     * <p>
     *     This method creates a {@link HealthCheck} instance with the current timestamp
     *     and persists it using the underlying repository. If the database operation fails,
     *     a {@code RuntimeException} is thrown.
     * </p>
    *
    * @return the saved {@link HealthCheck} object, including any populated fields (such as
    * an autogenerated ID) from the persistence layer
    *
    * @throws RuntimeException if the health check cannot be saved due to database
    * unavailability or other persistence errors
    */
    public HealthCheck recordHealthCheck() throws RuntimeException {
        try{
            HealthCheck healthCheck = new HealthCheck(LocalDateTime.now());
            return repository.save(healthCheck);
        } catch(Exception e){
            throw new RuntimeException("Failed to record health check - database unavailable", e);
        }
    }

    /**
     * Returns a list of all {@link HealthCheck} items stored in the repository
     *
     * <p>
     *     This method retrieves and returns a complete list of {@link HealthCheck} items.
     *     If the database operation fails, it throws a {@code RuntimeException}.
     * </p>
     *
     * @return a list of all {@link HealthCheck} items in the repository
     *
     * @throws RuntimeException if the operation fails due to database unavailability or
     * other persistence errors
     */
    public List<HealthCheck> getAllHealthChecks() {
        try {
            return repository.findAll();
        } catch(Exception e){
            throw new RuntimeException("Failed to return health checks - database unavailable", e);
        }
    }

    /**
     * Returns a count of health checks in the repository
     *
     * <p>
     *     This method returns the number of {@link HealthCheck} items stored in the repository.
     *     If the database operation fails, it throws a {@code RuntimeException}.
     * </p>
     *
     * @return the number of {@link HealthCheck} items in the repository
     *
     * @throws RuntimeException if the operation fails due to database unavailability or
     * other persistence errors
     */
    public long getHealthCheckCount() {
        try {
            return repository.count();
        } catch(Exception e){
            throw new RuntimeException("Failed to count number of health checks - database unavailable", e);
        }
    }
}
